[build]
  command = "yarn build"
  functions = "functions"
  publish = ".next"

[functions."commit-summary"]
  schedule = "@monthly"

[functions."commit-squares"]
  schedule = "@monthly"

[dev]
  autoLaunch = false